In [4]:
import numpy as np

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

In [7]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [12]:
b = a_centered [:, 0]
b


array([-1.,  0.,  1.,  1., -1.])

In [14]:
c = a_centered [:, 1]
c

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [17]:
a_centered_sp = b @ c
a_centered_sp

8.0

In [18]:
N = 5

In [19]:
display (a_centered_sp/(N-1))

2.0